# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73aa6901247925decbfb6d4cb2416458dd3b3c05f568e122367b34924556ebc01c7c63abaac1d72c3698f331d061621ba0a1e67d0c8fc92bb9b6d0c58b31532b

test:
  secret_key_base: 25b7ec26c0e8e7ce83b9a93f0b96835b7b78feded4269bfbe5db0f1623edae28dc6f25b76ea8d4984f5cb0d1a4883974249e2d8ee38996f73ff5d824ccb18dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
